let alumnograduacion_def_tests =[
    ['alumnograduacion', 'alumnograduacion_login', 1,'Comprobar tamaño mínimo login', 'ADD', 'ogin_min_size_KO', 'El login es inferior al tamaño mínimo. Debe estar entre 4 y 15 caracteres']
    ['alumnograduacion', 'alumnograduacion_login', 2, 'Comprobar tamaño máximo login', 'ADD', 'login_max_size_KO', 'El login excede el tamaño máximo. Debe estar entre 4 y 15 caracteres']
    ['alumnograduacion', 'alumnograduacion_login', 3, 'Comprobar tamaño formato login', 'ADD', 'login_format_KO', 'El login no cumple el formato. Debe estar entre 4 y 15 caracteres alfabéticos sin acentos ni ñ']
    ['alumnograduacion', 'alumnograduacion_login', 4, 'Comprobar campo válido login', 'ADD', true, '']
    ['alumnograduacion', 'alumnograduacion_login', 5,'Comprobar tamaño mínimo ogin', 'EDIT', 'login_min_size_KO', 'El login es inferior al tamaño mínimo. Debe estar entre 4 y 15 caracteres']
    ['alumnograduacion', 'alumnograduacion_login', 6, 'Comprobar tamaño máximo login', 'EDIT', 'login_max_size_KO', 'El login excede el tamaño máximo. Debe estar entre 4 y 15 caracteres']
    ['alumnograduacion', 'alumnograduacion_login', 7, 'Comprobar tamaño formato login', 'EDIT', 'login_format_KO', 'El Login no cumple el formato. Debe estar entre 4 y 15 caracteres alfabéticos sin acentos ni ñ']
    ['alumnograduacion', 'alumnograduacion_login', 8, 'Comprobar campo válido login', 'EDIT', true, '']
    ['alumnograduacion', 'alumnograduacion_login', 9, 'Comprobar tamaño máximo login', 'SEARCH', 'login_max_size_KO', 'El login excede el tamaño máximo. Debe estar entre 4 y 15 caracteres']
    ['alumnograduacion', 'alumnograduacion_login', 10, 'Comprobar tamaño formato login', 'SEARCH', 'login_format_KO', 'El login no cumple el formato. Debe estar entre 4 y 15 caracteres alfabéticos sin acentos ni ñ']
    ['alumnograduacion', 'alumnograduacion_login', 11, 'Comprobar campo válido login', 'SEARCH', true, '']

    ['alumnograduacion', 'alumnograduacion_password', 12, 'Comprobar tamaño mínimo password', 'ADD', 'password_min_size_KO', 'La password es inferior al tamaño mínimo. Debe estar entre 8 y 100 caracteres']
    ['alumnograduacion', 'alumnograduacion_password', 13, 'Comprobar tamaño máximo password', 'ADD', 'password_max_size_KO', 'La password excede al tamaño máximo. Debe estar entre 8 y 100 caracteres']
    ['alumnograduacion', 'alumnograduacion_password', 14, 'Comprobar formato password', 'ADD', 'password_format_KO', 'La password no cumple el formato. Debe estar entre 8 y 100 caracteres alfabéticos y espacios, sin acentos ni ñ']
    ['alumnograduacion', 'alumnograduacion_password', 15, 'Comprobar campo válido password', 'ADD', true, '']
    


] 

let alumnograduacion_tests_fields =[
    ['alumnograduacion', 'alumnograduacion_login', 1, 1, 'ADD', [{alumnograduacion_login: 'a'}], 'login_min_size_KO']
    ['alumnograduacion', 'alumnograduacion_login', 1, 2, 'ADD', [{alumnograduacion_login: 'ada'}], 'login_min_size_KO']
    ['alumnograduacion', 'alumnograduacion_login', 2, 3, 'ADD', [{alumnograduacion_login: 'a.repeat(15)'}], 'login_max_size_KO']
    ['alumnograduacion', 'alumnograduacion_login', 3, 4, 'ADD', [{alumnograduacion_login: 'martiño'}], 'login_format_KO']
    ['alumnograduacion', 'alumnograduacion_login', 3, 5, 'ADD', [{alumnograduacion_login: '#alicia'}], 'login_format_KO']
    ['alumnograduacion', 'alumnograduacion_login', 3, 6, 'ADD', [{alumnograduacion_login: 'maría'}], 'login_format_KO']
    ['alumnograduacion', 'alumnograduacion_login', 3, 7, 'ADD', [{alumnograduacion_login: 'sebas22'}], 'login_format_KO']
    ['alumnograduacion', 'alumnograduacion_login', 4, 8, 'ADD', [{alumnograduacion_login: 'javi'}], true]
    ['alumnograduacion', 'alumnograduacion_login', 5, 9, 'EDIT', [{alumnograduacion_login: 'a'}], 'login_min_size_KO']
    ['alumnograduacion', 'alumnograduacion_login', 5, 10, 'EDIT', [{alumnograduacion_login: 'ada'}], 'login_min_size_KO']
    ['alumnograduacion', 'alumnograduacion_login', 6, 11, 'EDIT', [{alumnograduacion_login: 'a.repeat(15)'}], 'login_max_size_KO']
    ['alumnograduacion', 'alumnograduacion_login', 7, 12, 'EDIT', [{alumnograduacion_login: 'martiño'}], 'login_format_KO']
    ['alumnograduacion', 'alumnograduacion_login', 7, 13, 'EDIT', [{alumnograduacion_login: '#alicia'}], 'login_format_KO']
    ['alumnograduacion', 'alumnograduacion_login', 7, 14, 'EDIT', [{alumnograduacion_login: 'maría'}], 'login_format_KO']
    ['alumnograduacion', 'alumnograduacion_login', 7, 15, 'EDIT', [{alumnograduacion_login: 'sebas22'}], 'login_format_KO']
    ['alumnograduacion', 'alumnograduacion_login', 8, 16, 'EDIT', [{alumnograduacion_login: 'javi'}], true]
    ['alumnograduacion', 'alumnograduacion_login', 9, 17, 'SEARCH', [{alumnograduacion_login: 'a.repeat(15)'}], 'login_max_size_KO']
    ['alumnograduacion', 'alumnograduacion_login', 10, 18, 'SEARCH', [{alumnograduacion_login: 'martiño'}], 'login_format_KO']
    ['alumnograduacion', 'alumnograduacion_login', 10, 19, 'SEARCH', [{alumnograduacion_login: '#alicia'}], 'login_format_KO']
    ['alumnograduacion', 'alumnograduacion_login', 10, 20, 'SEARCH', [{alumnograduacion_login: 'maría'}], 'login_format_KO']
    ['alumnograduacion', 'alumnograduacion_login', 10, 21, 'SEARCH', [{alumnograduacion_login: 'sebas22'}], 'login_format_KO']
    ['alumnograduacion', 'alumnograduacion_login', 11, 22, 'SEARCH', [{alumnograduacion_login: 'javi'}], true]

    ['alumnograduacion', 'alumnograduacion_password', 12, 23, 'ADD', [{password: 'f'}], 'password_min_size_KO']
    ['alumnograduacion', 'alumnograduacion_password', 12, 24, 'ADD', [{password: 'fffffff'}], 'password_min_size_KO']
    ['alumnograduacion', 'alumnograduacion_password', 13, 25, 'ADD', [{password: 'f.repeat(100)'}], 'password_max_size_KO']
    ['alumnograduacion', 'alumnograduacion_password', 14, 26, 'ADD', [{password: '34fifi98t'}], 'password_format_KO']
    ['alumnograduacion', 'alumnograduacion_password', 14, 27, 'ADD', [{password: '#midsomar'}], 'password_format_KO']
    ['alumnograduacion', 'alumnograduacion_password', 14, 28, 'ADD', [{password: 'San Martiño'}], 'password_format_KO']
    ['alumnograduacion', 'alumnograduacion_password', 14, 29, 'ADD', [{password: 'lucíaDerecho'}], 'password_format_KO']
    ['alumnograduacion', 'alumnograduacion_password', 15, 30, 'ADD', [{password: 'rlcfabiadice'}], true]

]